### ISSUE TITLE
Issue completing patcher

### ISSUE THREAD

**Issue by Perricolo** [gutieashl/SpellResearchAlternateTomePatcher#1]
Hey, I'm running into some issues completing the patcher for this. To the best of my knowledge, I have my settings for this set up correctly. I asked for help about it on the Synthesis discord and was recommended I open an issue here. I'm launching synthesis from mod organizer 2 and below is my log file for the failed patch. Any help would be appreciated, thanks!

[failed alt log.txt](https://github.com/gutieashl/SpellResearchAlternateTomePatcher/files/7967232/failed.alt.log.txt)

**Comment by gutieashl** [comment]
Can you also send the settings file 'Synthesis\Data\Skyrim Special Edition\SpellResearchAlternateTomePatcher\alteredtomesettings.json' so I can run against it

**Comment by Perricolo** [comment]
Hey. Sorry for the late reply, here ya go. It's in a zip because github won't let me send the .json file
[alteredtomesettings.zip](https://github.com/gutieashl/SpellResearchAlternateTomePatcher/files/7968291/alteredtomesettings.zip)

**Comment by gutieashl** [comment]
It happened because you have an empty line in your settings. I put a check that ignores empty lines and it should now work.

Also, your settings are a little off, it should be BaseMod;psc (e.g. 3DNPC.esp;spellresearch3dnpc.psc). Most of the time its smart enough to infer the mod from the psc, but there are exceptions.

**Comment by Perricolo** [comment]
Oh wow! thanks for the information, I honestly wouldn't have thought that would've mattered with the blank but that's good to know going forward. Also, the script file I'm referencing is coming from this mod https://www.nexusmods.com/skyrimspecialedition/mods/28816?tab=files which would mean the base mod is this mod... correct? Or do you mean the mod that the psc is relating to? My apologies if I misunderstood that.

**Comment by gutieashl** [comment]
No, the base mod is not the spell research patcher, it is the mod that introduces the spells. 

The mod you linked has a text file in the source folder with the correct formatting, just copy it from there.

**Comment by Perricolo** [comment]
Ohh I see okay, thanks again for the information!
