### ISSUE TITLE
CTD issue when opening inventory with a spell tome in it

### ISSUE THREAD

**Issue by audriuska12** [gutieashl/SpellResearchAlternateTomePatcher#3]
I'm going to move this to a separate issue - although I commented it on another issue's thread first, it occurred to me that I'm not sure if it actually notifies you properly, seeing as the issue is closed. Apologies if you were simply too busy to respond.

Trying to set up the patch for a larger load order, but it reproduces itself in a testing profile as well.
Running the patcher, then adding a Flames spell tome ( 0009cd51 ) to my inventory via console and trying to open the inventory causes an instant crash to desktop (doing this in the LAL starter cell.)
SSEdit shows the alterations to the tomes just fine, and the crash happens whether I'm using the ESP from the BSA version or the loose files version of the patch compendium. The premade ZPatches from the compendium work without any issue I can see.
The description mentions needing to copy the textures from the Spell Experience Book's BSA to the textures folder - that's done, the textures are in the Spell Experience Book Textures For ZPatcher mod and MO2 shows them in the path the description mentions.
https://modwat.ch/u/audriuska12
Crash log: https://drive.google.com/file/d/14yAkijZ_xSy6yymr0UklSAzt4KClebPz/view?usp=sharing
The only interesting thing I can see is the "Access violation - no RTTI data!" error in the crash log. From what little I can Google up, that seems like a potential mesh issue?

**Comment by gutieashl** [comment]
What settings do you use? your crash log mentions a $EverywhereMediumFont. Which I'm not sure about.
I don't think its the textures from spell experience book, it shouldn't crash if they are missing, it just wouldn't show them.
Also don't think its a mesh, your log doesn't seem to indicate any nifs.
Can you try disabling all the font/color/image settings and setting the font to a basic font like $SkyrimBooks

**Comment by audriuska12** [comment]
Disabled the font color/image checkboxes, picked $SkyrimBooks as the font for all of them. No success, and the crash log still claims $EverywhereMediumFont despite the description being:
<br><br><p align="center"><font face='$SkyrimBooks'><font size='40'></font>Flames<br><br></p>[pagebreak]<br><br><p align="left"><font face='$SkyrimBooks'><font size='40'></font>A novice spell of the destruction school, cast through immense concentration. This spell is fired where aimed. Elements of fire.</font></p>

MO2 shows no fontconfig.txt, unless it's being overwritten by something... in... a... BSA... actually, let me go and pull fontconfig.txt, fonts_en.swf and fonts_console.swf from Skyrim - Interface.bsa and put them as loose files to overwrite everything with.

And that didn't work either.

Would it be too much to ask what sort of a minimal LO you can make this work with?

...Oh, also. I'm not sure if it's relevant, but I'm running ENB - that's one thing that can't be changed quite as conveniently between setups. Disabling the effect in-game, at least, does not help.

**Comment by gutieashl** [comment]
It shouldn't be anything to be with ENB (I hope),

A minimal LO is just whatever mods you patch. For example, if you only patch spell books from skyrim.esm, a minimal load order would be skyrim.esm. You don't even need spellresearch.
The only thing this patcher does is change the description of the book, and clears the teaches spell flag (and sets the skill tought to null), it doesn't reference any records.

I created a test patch where I overrode the description of the flames tome with the description you copied here, cleared the teaches flag, and set the skill tought to 0, and it works.

I would guess you have some mod that maybe changes the typeface, or maybe corrupt world meshes for the books (which would cause a crash if the book got selected in the inventory menu, I doubt its corrupt meshes though). 

So I guess try a minimal LO and see if it works, then try to figure out whats causing the conflict, and please let me know when you find out.

**Comment by audriuska12** [comment]
...Okay, it appears to have worked. I can't _believe_ how silly of an error that was on my part, but it appears Synthesis simply wasn't complaining loud enough about not being updated _and_ doesn't seem to alert that the patch is too new for it. Updating everything that needed updating seems to have resolved the issue.

Attaching an extracted version of the Sparks record that consistently crashes the game if you feel like digging into it... but I expect the best use of everyone's time, especially yours, is to simply put a warning in the description for the next idiot of my caliber. 
[BookPatchTest.zip](https://github.com/gutieashl/SpellResearchAlternateTomePatcher/files/8217763/BookPatchTest.zip)

**Comment by gutieashl** [comment]
It has the teaches flag set, while the teaches spell is null which will certainly cause the game to crash. As you said, its due to an older version of mutagen.
